config/routes.rb
Rails.application.routes.draw do
  resources :service_managements
  # Devise
  devise_for :users,  controllers: { registrations: 'registrations' },
                      path: '',
                      path_names: { sign_in: 'login',
                                    sign_out: 'logout',
                                    sign_up: 'register' }
                                    
  # Contacts
  resources :contacts, only: %i[new create]

  # Pages
  get '/home', to:'pages#home'
  get '/nosotros', to:'pages#nosotros'
  get '/servicios', to:'pages#servicios'
  get '/contacto', to:'pages#contacto'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/client.rb
class Client < ApplicationRecord
    # Validaciones
    validates :name,    presence: true
    validates :email,   presence: true,
end

app/models/contact.rb
# == Schema Information
#
# Table name: contacts
#
#  id         :bigint           not null, primary key
#  name       :string
#  email      :string
#  message    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Contact < ApplicationRecord
    # Validaciones
    validates :name,    presence: true
    validates :email,   presence: true,
                        format: { with: URI::MailTo::EMAIL_REGEXP }
    validates :message, presence: true
  end

app/models/repair.rb
class Repair < ApplicationRecord
    #validaciones
    validates :name, presence: true
end

app/models/service.rb
class Service < ApplicationRecord
    #validaciones
    validates :name, presence: true
end

app/models/service_management.rb
class ServiceManagement < ApplicationRecord
  belongs_to :client
  belongs_to :contact
  belongs_to :vehiculo
  belongs_to :repair
  belongs_to :service
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

  # relaciones
  has_many :contacts, dependent: :destroy
end

app/models/vehiculo.rb
class Vehiculo < ApplicationRecord
    #validaciones
    validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pagy::Backend
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # POST /contacts or /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to root_path, notice: "Contact was successfully created." }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:name, :email, :message)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def nosotros
  end

  def servicios
  end

  def contacto
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    added_attrs = %i[ email password password_confirmation remember_me ]

    devise_parameter_sanitizer.permit :sign_up, keys: %i[email password password_confirmation ]
    devise_parameter_sanitizer.permit :sign_in, keys: %i[email password remember_me]
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end

  def update_resource(resource, params)
    resource.update_without_password(params)
  end
end

app/controllers/service_managements_controller.rb
class ServiceManagementsController < ApplicationController
  before_action :set_service_management, only: %i[ show edit update destroy ]

  # GET /service_managements or /service_managements.json
  def index
    @service_managements = ServiceManagement.all
  end

  # GET /service_managements/1 or /service_managements/1.json
  def show
  end

  # GET /service_managements/new
  def new
    @service_management = ServiceManagement.new
  end

  # GET /service_managements/1/edit
  def edit
  end

  # POST /service_managements or /service_managements.json
  def create
    @service_management = ServiceManagement.new(service_management_params)

    respond_to do |format|
      if @service_management.save
        format.html { redirect_to service_management_url(@service_management), notice: "Service management was successfully created." }
        format.json { render :show, status: :created, location: @service_management }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @service_management.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /service_managements/1 or /service_managements/1.json
  def update
    respond_to do |format|
      if @service_management.update(service_management_params)
        format.html { redirect_to service_management_url(@service_management), notice: "Service management was successfully updated." }
        format.json { render :show, status: :ok, location: @service_management }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @service_management.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /service_managements/1 or /service_managements/1.json
  def destroy
    @service_management.destroy

    respond_to do |format|
      format.html { redirect_to service_managements_url, notice: "Service management was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service_management
      @service_management = ServiceManagement.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def service_management_params
      params.require(:service_management).permit(:client_id, :contact_id, :vehiculo_id, :repair_id, :service_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/service_managements_helper.rb
module ServiceManagementsHelper
end

app/views/contacts/_form.html.erb
<%= form_with(model: contact) do |form| %>
  <% if contact.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
        <% contact.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, required:true %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email, required:true%>
  </div>

  <div>
    <%= form.label :message, style: "display: block" %>
    <%= form.text_area :message, required:true %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= render "form", contact: @contact %>

<br>

<div>
  <%= link_to "Back to contacts", contacts_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>El Tuercas</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </head>

  <body>
    <%=render "shared/navbar"%>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
      <div class="container">
        <div class="row">
          <div class="col">
            <%= yield %>
          </div>
        </div>
      </div> 
      </div>
    </div>
  </body>

  <footer>
    <%=render "shared/footer"%>
  </footer>

</html>

app/views/pages/contacto.html.erb
<div class="container">
    <div class="col">
    <div class="mb-3">
        <h2>¡Contáctanos!</h2>
        <p>¿Necesitas programar una cita o tienes preguntas sobre nuestros servicios? No dudes en ponerte en contacto con nosotros. Estamos aquí para ayudarte a mantener tu vehículo en óptimas condiciones.</p>
        <br>
        <h3>¡Ponte en contacto con nosotros!</h3>
    </div>
    <div class="mb-3">
        <label for="exampleFormControlInput1" class="form-label">Email</label>
        <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="correo@correo.com">
    </div>
    <div class="mb-3">
        <label for="exampleFormControlTextarea1" class="form-label">Mensaje</label>
        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
    </div>
    <div class="mb-3" style="text-align: center;">
        <h3>Estamos ubicados en:</h3>
    <br>
        <div class="map-responsive">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d8691.32529097523!2d-70.62593070385387!3d-33.62980539990683!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x9662d7497944b90f%3A0xf557b8ed7ed6095c!2sTALLER%20MECANICO%20FENIX!5e0!3m2!1ses-419!2scl!4v1730241273216!5m2!1ses-419!2scl" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
        </div>
    </div>
    </div>
</div>

app/views/pages/home.html.erb
<div class="contained">
	<div class="row">
		<div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
			<div class="carousel-inner">
			<div class="carousel-item active">
			<img src="..." class="d-block w-100" alt="...">
			</div>
			<div class="carousel-item">
			<img src="..." class="d-block w-100" alt="...">
			</div>
			<div class="carousel-item">
			<img src="..." class="d-block w-100" alt="...">
			</div>
			<h1>Bienvenido a El Tuercas</h1>
			<p>Somos tu taller mecánico de confianza en Santiago que te ofrece un servicio de 
				primera clase para mantener tu vehículo en perfecto estado. En El Tuercas, 
				entendemos la importancia de tu automóvil y nos comprometemos a brindarte soluciones 
				de calidad con un toque personal.</p>
			</div>
		</div>
	</div>
</div>

app/views/pages/nosotros.html.erb
<h1>Pages#nosotros</h1>
<p>Find me in app/views/pages/nosotros.html.erb</p>

app/views/pages/servicios.html.erb
<div class="row row-cols-1 row-cols-md-2 g-4">
  <div class="col">
    <div class="card">
      <img src="..." class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card">
      <img src="..." class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card">
      <img src="..." class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content.</p>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card">
      <img src="..." class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
      </div>
    </div>
  </div>
</div>

app/views/service_managements/_form.html.erb
<%= form_with(model: service_management) do |form| %>
  <% if service_management.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(service_management.errors.count, "error") %> prohibited this service_management from being saved:</h2>

      <ul>
        <% service_management.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :client_id, style: "display: block" %>
    <%= form.text_field :client_id %>
  </div>

  <div>
    <%= form.label :contact_id, style: "display: block" %>
    <%= form.text_field :contact_id %>
  </div>

  <div>
    <%= form.label :vehiculo_id, style: "display: block" %>
    <%= form.text_field :vehiculo_id %>
  </div>

  <div>
    <%= form.label :repair_id, style: "display: block" %>
    <%= form.text_field :repair_id %>
  </div>

  <div>
    <%= form.label :service_id, style: "display: block" %>
    <%= form.text_field :service_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/service_managements/_service_management.html.erb
<div id="<%= dom_id service_management %>">
  <p>
    <strong>Client:</strong>
    <%= service_management.client.name %>
  </p>

  <p>
    <strong>Contact:</strong>
    <%= service_management.contact.name %>
  </p>

  <p>
    <strong>Vehiculo:</strong>
    <%= service_management.vehiculo.name %>
  </p>

  <p>
    <strong>Repair:</strong>
    <%= service_management.repair.name %>
  </p>

  <p>
    <strong>Service:</strong>
    <%= service_management.service.name %>
  </p>

</div>

app/views/service_managements/edit.html.erb
<h1>Editing service management</h1>

<%= render "form", service_management: @service_management %>

<br>

<div>
  <%= link_to "Show this service management", @service_management %> |
  <%= link_to "Back to service managements", service_managements_path %>
</div>

app/views/service_managements/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Service managements</h1>

<div id="service_managements">
  <% @service_managements.each do |service_management| %>
    <%= render service_management %>
    <p>
      <%= link_to "Show this service management", service_management %>
    </p>
  <% end %>
</div>

<%= link_to "New service management", new_service_management_path %>

app/views/service_managements/new.html.erb
<h1>New service management</h1>

<%= render "form", service_management: @service_management %>

<br>

<div>
  <%= link_to "Back to service managements", service_managements_path %>
</div>

app/views/service_managements/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @service_management %>

<div>
  <%= link_to "Edit this service management", edit_service_management_path(@service_management) %> |
  <%= link_to "Back to service managements", service_managements_path %>

  <%= button_to "Destroy this service management", @service_management, method: :delete %>
</div>

app/views/shared/_footer.html.erb
<!-- footer -->
<footer class="py-lg-8 py-5 footer bg-dark">
  <div class="container">
    <div class="row gy-4">
      <div class="col-lg-4 col-12">
        <!-- about company -->
        <div class="d-flex flex-column gap-4">
          <div>
            <img src="../assets/images/mentor/geeks-mentor.svg" alt="Geeks" class="logo-reverse" />
          </div>
          <div>
            <p class="mb-0 txet-gray-500">Connecting founders and marketers with battle-hardened mentors that genuinely enjoy helping people.</p>
          </div>
          <!-- Instagram -->
          <div class="fs-4 d-flex flex-row gap-3">
            <a href="#!" class="text-reset">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-instagram" viewBox="0 0 16 16">
                <path
                  d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z" />
              </svg>
            </a>
            <!--Facebook-->
            <a href="#!" class="text-reset">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-facebook" viewBox="0 0 16 16">
                <path
                  d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z" />
              </svg>
            </a>
            <!--Twitter-->
            <a href="#!" class="text-reset">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-twitter-x" viewBox="0 0 16 16">
                <path d="M12.6.75h2.454l-5.36 6.142L16 15.25h-4.937l-3.867-5.07-4.425 5.07H.316l5.733-6.57L0 .75h5.063l3.495 4.633L12.601.75Zm-.86 13.028h1.36L4.323 2.145H2.865z" />
              </svg>
            </a>
            <!--youtube-->
            <a href="#!" class="text-reset">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-youtube" viewBox="0 0 16 16">
                <path
                  d="M8.051 1.999h.089c.822.003 4.987.033 6.11.335a2.01 2.01 0 0 1 1.415 1.42c.101.38.172.883.22 1.402l.01.104.022.26.008.104c.065.914.073 1.77.074 1.957v.075c-.001.194-.01 1.108-.082 2.06l-.008.105-.009.104c-.05.572-.124 1.14-.235 1.558a2.01 2.01 0 0 1-1.415 1.42c-1.16.312-5.569.334-6.18.335h-.142c-.309 0-1.587-.006-2.927-.052l-.17-.006-.087-.004-.171-.007-.171-.007c-1.11-.049-2.167-.128-2.654-.26a2.01 2.01 0 0 1-1.415-1.419c-.111-.417-.185-.986-.235-1.558L.09 9.82l-.008-.104A31 31 0 0 1 0 7.68v-.123c.002-.215.01-.958.064-1.778l.007-.103.003-.052.008-.104.022-.26.01-.104c.048-.519.119-1.023.22-1.402a2.01 2.01 0 0 1 1.415-1.42c.487-.13 1.544-.21 2.654-.26l.17-.007.172-.006.086-.003.171-.007A100 100 0 0 1 7.858 2zM6.4 5.209v4.818l4.157-2.408z" />
              </svg>
            </a>
          </div>
        </div>
      </div>
      <div class="col-lg-2 col-md-3 col-6">
        <div class="d-flex flex-column gap-2">
          <!-- list -->
          <h5 class="fw-bold text-white text-uppercase mb-0">Platform</h5>
          <ul class="list-unstyled nav nav-footer flex-column nav-x-0">
            <li><a href="#" class="nav-link">Browse Mentors</a></li>
            <li><a href="#" class="nav-link">Book a Session</a></li>
            <li><a href="#" class="nav-link">Become a Mentor</a></li>
            <li><a href="#" class="nav-link">Wall Of love</a></li>
          </ul>
        </div>
      </div>
      <div class="col-lg-2 col-md-3 col-6">
        <div class="d-flex flex-column gap-2">
          <!-- list -->
          <h5 class="fw-bold text-white text-uppercase mb-0">Resources</h5>
          <ul class="list-unstyled nav nav-footer flex-column nav-x-0">
            <li><a href="#" class="nav-link">Newsletter</a></li>
            <li><a href="#" class="nav-link">Case Studies</a></li>
            <li><a href="#" class="nav-link">Books</a></li>
            <li><a href="#" class="nav-link">Templates</a></li>
            <li><a href="#" class="nav-link">Blog</a></li>
          </ul>
        </div>
      </div>
      <div class="col-lg-2 col-md-3 col-6">
        <div class="d-flex flex-column gap-2">
          <!-- list -->
          <h5 class="fw-bold text-white text-uppercase mb-0">Company</h5>
          <ul class="list-unstyled nav nav-footer flex-column nav-x-0">
            <li><a href="#" class="nav-link">About</a></li>
            <li><a href="#" class="nav-link">Partner Program</a></li>
            <li><a href="#" class="nav-link">Privacy Policy</a></li>
            <li><a href="#" class="nav-link">Meet the Team</a></li>
          </ul>
        </div>
      </div>
      <div class="col-lg-2 col-md-3 col-6">
        <div class="d-flex flex-column gap-2">
          <!-- list -->
          <h5 class="fw-bold text-white text-uppercase mb-0">Support</h5>
          <ul class="list-unstyled nav nav-footer flex-column nav-x-0">
            <li><a href="#" class="nav-link">FAQ</a></li>
            <li><a href="#" class="nav-link">Contact</a></li>
            <li><a href="#" class="nav-link">Help centre</a></li>
            <li><a href="#" class="nav-link">Join Community</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="row mt-lg-7 mt-5">
      <!-- Desc -->
      <div class="col-lg-6 offset-lg-3 col-12">
        <span class="d-flex justify-content-center">
          ©
          <span id="copyright2" class="me-2">
            <script>
              document.getElementById("copyright2").appendChild(document.createTextNode(new Date().getFullYear()));
            </script>
          </span>
          Geeks-UI Mentor. All Rights Reserved.
        </span>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container">
    <%= link_to "El Tuercas", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <%= link_to "Nosotros", nosotros_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to "Servicios", servicios_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to "Contacto", contacto_path, class: "nav-link" %>
        </li>
        </ul>
        <nav class="navbar bg-body-tertiary">
            <form class="container-fluid justify-content-start">
            <%= link_to "Inicio Sesion", new_user_registration_path , class: "btn btn-sm btn-outline-secondary" %>
            <%= link_to "Cerrar Sesion", new_user_session_path , class: "btn btn-sm btn-outline-secondary" %>
            </form>
</nav>
    </div>
</nav>